# Generated by Django 5.0.2 on 2024-02-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
